sudo: required # route your build to the container-based infrastructure for a faster build

language: ruby

rvm:
  - 2.4.1


branches:
  only:
  - master

cache: 
  - bundler # caching bundler gem packages will speed up build

jobs:
  include:
    - stage: "Build"
      script:
        - bundle exec jekyll build
    - stage: "Deploy"
      deploy:
        - provider: s3
          access_key_id: "$AWS_ACCESS_KEY_ID"
          secret_access_key: "$AWS_SECRET_ACCESS_KEY"
          bucket: "$S3_BUCKET"
          skip_cleanup: true
          region: us-east-1
          local_dir: _site 
    - stage: "Invalidate Cache"
      script: pip install --user awscli
      script: export PATH=$PATH:$HOME/.local/bin # put aws in the path
      script: aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /*

